#!/usr/bin/env tsx
import { writeFileSync, mkdirSync, readFileSync } from "fs";
import { join } from "path";
import config from "../app/config.js";
import { resolveConfig } from "./lib/resolve-config.js";
import { green } from "./lib/console-color.js";

const publicDir = join(process.cwd(), "public");

let resolved;
try {
  resolved = resolveConfig(config, (src) =>
    readFileSync(join(publicDir, src), "utf-8"),
  );
} catch (error) {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
}

const outputDir = join(process.cwd(), "generated");
mkdirSync(outputDir, { recursive: true });
const outputPath = join(outputDir, "config.ts");
writeFileSync(
  outputPath,
  `// AUTO-GENERATED by \`pnpm generate:config\` from app/config.ts. Do not edit directly.
import { Config } from "../app/config.types";

const config: Config = ${JSON.stringify(resolved, null, 2)};

export default config;
`,
  "utf-8",
);

console.log(` ${green("✓")} Generated generated/config.ts from app/config.ts`);
